pipelines:
  branches:
    production:
    - step:
        name: Creating FreeCAD image and pushing to Docker Hub
        image: atlassian/default-image:2
        services:
          - docker
        script:
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t keletes/freecad:latest .
          - docker push keletes/freecad:latest
        caches:
          - docker
          - node